Server:
  port: 2222
  tomcat:
    threads:
      max: 100
      min-spare: 25
    accept-count: 15000

spring:
  application:
    name: zzzz.com
  #DBS
  datasource:
    hikari:
      maximum-pool-size: 20 #so luong toi da ket noi
      minimum-idle: 5       #so luong toi thieu ket noi
    url: jdbc:mysql://localhost:3316/vetautet
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none  #khong auto create/update table
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  jackson:
    serialization:
      indent_output: true
  #Redis server connection setting
  data:
    redis:
      host: 127.0.0.1 #host of the redis server
      port: 6319 #port of the redis server for connection
      password: ""
      lettuce:
        pool:
          max-active: 100 #so luong toi da ket noi
          max-idle: 10 #so luong toi thieu ket noi
          min-idle: 5 #so luong toi thieu ket noi
      connection-timeout: 30000 #thoi gian ket noi
  #Thread virtual
  thread:
    virtual:
      enabled: true

#Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      backendA:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
       # slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

  ratelimiter:
    instances:
      backendA:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
      backendB:
        limitForPeriod: 6
        limitRefreshPeriod: 500ms
        timeoutDuration: 3s
management:
  health:
    circuitbreakers:
      enabled: true
    endpoints:
      web:
        exposure:
          include: "*"

    endpoint:
      health:
        show-details: ALWAYS
      prometheus:
        enabled: true
